name: garden_glossary
description: "Front-end for a mobile application that identifies a plant photo and returns key information about the plant from RHS or Anthropic's Claude."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  dio: ^5.8.0
  flutter_launcher_icons: ^0.14.3
  cached_network_image: ^3.4.1
  flutter_image_compress: ^2.4.0
  mime: ^2.0.0
  logging: ^1.3.0
  shared_preferences: ^2.5.3
  flutter_riverpod: ^2.6.1
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  gal: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Cormorant
      fonts:
        - asset: assets/fonts/Cormorant-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cormorant-Bold.ttf
          weight: 700
  assets:
    - assets/images/background.jpg
    - assets/images/icon.png
    - assets/images/icon_background.png
    - .env
    - .env.prod
    - .env.dev
    - .env.local
    - .env.mock

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_foreground: "assets/images/icon.png"  # (For Android adaptive icons)
  adaptive_icon_background: "assets/images/icon_background.png"  # (For Android adaptive icons)

